import json
from unittest.mock import MagicMock

import pytest

from buttermilk._core.processing_context import ProcessingContext
from buttermilk._core.types import Record
from buttermilk._core.vertex_batch import BatchJobManager
from buttermilk.processors.vertex_batch import VertexBatchProcessor


def _wrap_records(records: list[Record]) -> list[ProcessingContext]:
    """Wrap records in minimal ProcessingContexts for batch processor calls."""
    return [ProcessingContext(session_id="test", record=r) for r in records]


class TestVertexBatchFileProduction:
    """End-to-end test for Vertex Batch file production logic.

    Validates that the JSONL generated by the system matches the schema
    expected by Vertex AI Batch API for both Gemini and Claude models.
    """

    @pytest.mark.slow
    def test_gemini_jsonl_structure(self, real_bm):
        """Verify Gemini JSONL output structure matches Vertex Batch API requirements.

        This test checks the Google 'Generative AI' schema which is required for
        Gemini models on Vertex AI.

        Schema verification focus:
        - `request.contents`: The main payload container.
        - `contents[0].parts[0].text`: Where the actual user prompt lives.
        - `contents[0].role`: Must be "user".
        """
        # Setup
        processor = VertexBatchProcessor(
            name="test_batch_gemini",
            model="gemini-1.5-flash",
            template="simple",
            template_vars={"var": "default"},
            fail_on_unfilled_parameters=False,
        )

        records = [
            Record(
                record_id=f"rec_{i}",
                content=f"Ignored Content {i}",
                metadata={"var": f"Content {i}"},  # Inject into template variable {{var}}
            )
            for i in range(3)
        ]

        # Execution
        requests = processor.prepare_batch_requests(_wrap_records(records))

        # Build JSONL
        manager = BatchJobManager(client=MagicMock())
        jsonl = manager.build_jsonl(requests, model="gemini-1.5-flash")

        # Verification
        lines = jsonl.strip().split("\n")
        assert len(lines) == 3

        for i, line in enumerate(lines):
            entry = json.loads(line)

            # Top level structure
            assert "custom_id" in entry, f"Missing custom_id in line {i}"
            assert "request" in entry, f"Missing request object in line {i}"

            # Request structure for Gemini
            req = entry["request"]
            assert "contents" in req, f"Missing contents in request line {i}"
            assert len(req["contents"]) == 1
            assert req["contents"][0]["role"] == "user"

            # Check expected templated output
            expected_text = f"Process this input: Content {i}"
            assert req["contents"][0]["parts"][0]["text"] == expected_text

            # Check system instruction (simple template has a system prompt)
            assert "system_instruction" in req, f"Missing system_instruction in line {i}"
            assert req["system_instruction"]["parts"][0]["text"] == "You are a helpful assistant."

    @pytest.mark.slow
    def test_claude_jsonl_structure(self, real_bm):
        """Verify Claude JSONL output structure matches Vertex Batch API requirements.

        This test checks the Anthropic 'Messages' schema adapter which is required
        for Claude models on Vertex AI.

        Schema verification focus:
        - `request.anthropic_version`: Required version string (e.g., "vertex-2023-10-16").
        - `request.messages`: Anthropic-style message history.
        - `messages[0].content`: The user message content.
        """
        # Setup
        processor = VertexBatchProcessor(
            name="test_batch_claude",
            model="claude-3-5-sonnet",
            template="simple",
            template_vars={"var": "default"},
            fail_on_unfilled_parameters=False,
        )

        records = [
            Record(
                record_id="rec_claude",
                content="Ignored Content",
                metadata={"var": "Claude Content"},  # Inject into template variable {{var}}
            )
        ]

        # Execution
        requests = processor.prepare_batch_requests(_wrap_records(records))

        # Build JSONL
        manager = BatchJobManager(client=MagicMock())
        jsonl = manager.build_jsonl(requests, model="claude-3-5-sonnet")

        # Verification
        entry = json.loads(jsonl.strip())

        # Request structure for Claude
        req = entry["request"]
        assert "anthropic_version" in req, "Missing anthropic_version"
        assert "messages" in req, "Missing messages"
        assert len(req["messages"]) == 1
        assert req["messages"][0]["role"] == "user"

        # Check content
        msg_content = req["messages"][0]["content"]
        expected_text = "Process this input: Claude Content"

        if isinstance(msg_content, list):
            assert msg_content[0]["text"] == expected_text
        else:
            assert msg_content == expected_text

        # Check system instruction
        assert "system" in req, "Missing system field"
        assert req["system"] == "You are a helpful assistant."


class TestVertexBatchDryRun:
    """Tests for VertexBatchProcessor dry-run mode.

    Dry-run mode writes batch JSONL to GCS without submitting to API.
    """

    @pytest.mark.anyio
    async def test_dry_run_writes_to_gcs(self, real_bm, mocker):
        """Verify dry_run=True writes batch JSONL to GCS but does not submit job.

        When dry_run is enabled:
        - Template rendering and message preparation should happen
        - JSONL file should be written to GCS
        - Records should be returned with dry_run metadata including GCS URI
        - No batch job API calls should be made
        """
        # Mock the GCS upload - patch both where defined and where imported
        mock_upload = mocker.patch(
            "buttermilk.utils.save.upload_text",
            return_value="gs://test-bucket/dry_run_abc123/input.jsonl",
        )
        mocker.patch(
            "buttermilk._core.vertex_batch.upload_text",
            return_value="gs://test-bucket/dry_run_abc123/input.jsonl",
        )

        # Mock the manager's _resolve_batch_dir to avoid bm dependency
        mocker.patch.object(
            BatchJobManager,
            "_resolve_batch_dir",
            return_value="gs://test-bucket/dry_run_abc123",
        )

        processor = VertexBatchProcessor(
            name="test_dry_run",
            model="gemini-1.5-flash",
            template="simple",
            template_vars={"var": "default"},
            fail_on_unfilled_parameters=False,
            dry_run=True,
        )

        # Mock _ensure_manager to return a mock manager with realistic client
        mock_client = MagicMock()
        mock_client._location = "us-central1"
        mock_manager = BatchJobManager(client=mock_client)
        mocker.patch.object(processor, "_ensure_manager", return_value=mock_manager)

        records = [
            Record(
                record_id=f"dry_run_{i}",
                content=f"Test content {i}",
                metadata={"var": f"Dry run content {i}"},
            )
            for i in range(3)
        ]

        # Process with dry_run=True
        results = await processor._process_batch(_wrap_records(records))

        # Verify GCS upload was called with JSONL content
        mock_upload.assert_called_once()
        call_args = mock_upload.call_args
        jsonl_content = call_args[0][0]  # First positional arg is content
        assert "custom_id" in jsonl_content  # JSONL should have batch request structure
        assert call_args[1]["content_type"] == "application/jsonl"

        # Should return same number of records
        assert len(results) == 3

        # Each record should have dry_run metadata with GCS URI
        for i, result in enumerate(results):
            assert result.metadata.get("dry_run") is True
            assert result.metadata.get("batch_status") == "dry_run"
            assert result.metadata.get("model") == "gemini-1.5-flash"
            assert result.metadata.get("template") == "simple"
            assert result.metadata.get("dry_run_uri") == "gs://test-bucket/dry_run_abc123/input.jsonl"
            assert result.metadata.get("dry_run_job_id") is not None
            assert result.metadata["dry_run_job_id"].startswith("dry_run_")
            # Original record_id should be preserved
            assert result.record_id == f"dry_run_{i}"

    @pytest.mark.anyio
    async def test_dry_run_false_default_behavior(self):
        """Verify dry_run defaults to False and doesn't affect normal operation.

        This test just verifies the flag defaults correctly.
        Full API integration is tested elsewhere.
        """
        processor = VertexBatchProcessor(
            name="test_default",
            model="gemini-1.5-flash",
            template="simple",
            template_vars={"var": "default"},
            fail_on_unfilled_parameters=False,
        )

        # Default should be False
        assert processor.dry_run is False

    def test_dry_run_prepare_batch_requests_still_works(self, real_bm):
        """Verify prepare_batch_requests works normally with dry_run=True.

        Dry-run mode should not affect the request preparation logic.
        """
        processor = VertexBatchProcessor(
            name="test_dry_run_prepare",
            model="gemini-1.5-flash",
            template="simple",
            template_vars={"var": "default"},
            fail_on_unfilled_parameters=False,
            dry_run=True,
        )

        records = [
            Record(
                record_id="prepare_test",
                content="Test",
                metadata={"var": "Prepared content"},
            )
        ]

        # prepare_batch_requests should work identically
        requests = processor.prepare_batch_requests(_wrap_records(records))

        assert len(requests) == 1
        assert requests[0].record_id == "prepare_test"
        assert len(requests[0].messages) > 0
