import json
from unittest.mock import MagicMock

import pytest

from buttermilk._core.types import Record
from buttermilk._core.vertex_batch import BatchJobManager
from buttermilk.processors.vertex_batch import VertexBatchProcessor


class TestVertexBatchFileProduction:
    """End-to-end test for Vertex Batch file production logic.

    Validates that the JSONL generated by the system matches the schema
    expected by Vertex AI Batch API for both Gemini and Claude models.
    """

    @pytest.mark.endtoend
    def test_gemini_jsonl_structure(self):
        """Verify Gemini JSONL output structure matches Vertex Batch API requirements.

        This test checks the Google 'Generative AI' schema which is required for
        Gemini models on Vertex AI.

        Schema verification focus:
        - `request.contents`: The main payload container.
        - `contents[0].parts[0].text`: Where the actual user prompt lives.
        - `contents[0].role`: Must be "user".
        """
        # Setup
        processor = VertexBatchProcessor(
            name="test_batch_gemini",
            model="gemini-1.5-flash",
            template="simple",
            template_vars={"var": "default"},
            fail_on_unfilled_parameters=False,
        )

        records = [
            Record(
                record_id=f"rec_{i}",
                content=f"Ignored Content {i}",
                metadata={"var": f"Content {i}"},  # Inject into template variable {{var}}
            )
            for i in range(3)
        ]

        # Execution
        requests = processor.prepare_batch_requests(records)

        # Build JSONL
        manager = BatchJobManager(client=MagicMock())
        jsonl = manager.build_jsonl(requests, model="gemini-1.5-flash")

        # Verification
        lines = jsonl.strip().split("\n")
        assert len(lines) == 3

        for i, line in enumerate(lines):
            entry = json.loads(line)

            # Top level structure
            assert "custom_id" in entry, f"Missing custom_id in line {i}"
            assert "request" in entry, f"Missing request object in line {i}"

            # Request structure for Gemini
            req = entry["request"]
            assert "contents" in req, f"Missing contents in request line {i}"
            assert len(req["contents"]) == 1
            assert req["contents"][0]["role"] == "user"

            # Check expected templated output
            expected_text = f"Process this input: Content {i}"
            assert req["contents"][0]["parts"][0]["text"] == expected_text

            # Check system instruction (simple template has a system prompt)
            assert "system_instruction" in req, f"Missing system_instruction in line {i}"
            assert req["system_instruction"]["parts"][0]["text"] == "You are a helpful assistant."

    @pytest.mark.endtoend
    def test_claude_jsonl_structure(self):
        """Verify Claude JSONL output structure matches Vertex Batch API requirements.

        This test checks the Anthropic 'Messages' schema adapter which is required
        for Claude models on Vertex AI.

        Schema verification focus:
        - `request.anthropic_version`: Required version string (e.g., "vertex-2023-10-16").
        - `request.messages`: Anthropic-style message history.
        - `messages[0].content`: The user message content.
        """
        # Setup
        processor = VertexBatchProcessor(
            name="test_batch_claude",
            model="claude-3-5-sonnet",
            template="simple",
            template_vars={"var": "default"},
            fail_on_unfilled_parameters=False,
        )

        records = [
            Record(
                record_id="rec_claude",
                content="Ignored Content",
                metadata={"var": "Claude Content"},  # Inject into template variable {{var}}
            )
        ]

        # Execution
        requests = processor.prepare_batch_requests(records)

        # Build JSONL
        manager = BatchJobManager(client=MagicMock())
        jsonl = manager.build_jsonl(requests, model="claude-3-5-sonnet")

        # Verification
        entry = json.loads(jsonl.strip())

        # Request structure for Claude
        req = entry["request"]
        assert "anthropic_version" in req, "Missing anthropic_version"
        assert "messages" in req, "Missing messages"
        assert len(req["messages"]) == 1
        assert req["messages"][0]["role"] == "user"

        # Check content
        msg_content = req["messages"][0]["content"]
        expected_text = "Process this input: Claude Content"

        if isinstance(msg_content, list):
            assert msg_content[0]["text"] == expected_text
        else:
            assert msg_content == expected_text

        # Check system instruction
        assert "system" in req, "Missing system field"
        assert req["system"] == "You are a helpful assistant."
