defaults:
  - _self_
  # - criteria@batch.params.criteria: trans
  - agents@batch.agents:
      - manager
      - judge
      # - synth
      - scorer
      # - differences

batch:
  _target_: buttermilk.runner.groupchat.AutogenOrchestrator
  description: Applies criteria from advocacy and journalism organisations for high quality reporting on trans issues.
  name: trans
  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index:
        - record_id
  params:
    criteria:
      - tja
    task: Assess this content.
  tools:
    spy:
      name: "🕵️spy"
      description: Log agent outputs to Bigquery
      role: spy
      agent_obj: SpyAgent
      save_dest:
        type: bq
        dataset: prosocial-443205.testing.flow
        db_schema: flow.json

  agents:
    host:
      role: HOST
      name: "🎯 Sequence Host"
      description: Run through a defined sequence of steps.
      agent_obj: Sequencer
      num_runs: 1
      parameters: {}
      inputs:
        participants:
