# defaults:
#   - _self_

chat:
  _target_: buttermilk.runner.moa.MoA
  source: trans journalists guidelines interactive
  save: ${save}
  conductor: FFA

  steps:
    - name: fetch
      agent: Fetch
      description: fetch urls and stored records for the chat
      data:
        - name: tja_train
          type: file
          path: gs://prosocial-dev/data/tja_train.jsonl
          index:
            - record_id
      inputs:
        prompt: prompt

    - name: general
      description: An expert analyst with relevant subject-matter expertise.
      agent: LLMAgent
      num_runs: 1
      variants:
        template: groupchat
        model: ${llms.general}
        criteria:
          - trans_simplified
          - cte
          - tja
          - glaad
          - hrc
          - trans_factored
        formatting: json_rules
