
context:
  _target_: buttermilk.runner.flow.Flow
  source: context describer test

  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index: 
        - record_id

  steps:
    - name: context
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters: 
        template: context
        model: ${llm}
      inputs:
        record: record
      outputs:
        context: description