defaults:
  - _self_

describer:
  _target_: buttermilk.runner.flow.Flow
  source: api development
  steps: 

    - name: describer
      _target_: buttermilk.agents.describer.Describer
      num_runs: 1
      parameters: 
        download_if_necessary: true
        template: describe
        model:
          - gemini15pro
      inputs:
        record: record
      
    # - name: describe_synth
    #   _target_: buttermilk.agents.lc.LC
    #   num_runs: 1
    #   concurrency: 20
    #   parameters: 
    #     template: synthesise
    #     model:
    #       - gpt4v
    #       - gemini15pro
    #       - sonnet
    #   inputs:
    #     record: record
    #     answers: describe.outputs
    #   outputs:
    #     record: outputs