defaults:
  - describer
  - _self_

params:
  template: frames
  model:
    - gpt4o
    - gemini15pro
    - sonnet
    - llama32_90b_vision_instruct_azure

frames:
  _target_: buttermilk.runner.creek.Creek
  source: api development
  steps: 
    - name: frames
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      parameters: ${flows.params}
      inputs:
        record: record
    - name: frames_synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      parameters: ${flows.params}
      inputs:
        record: record
        answers: frames.outputs
      outputs:
        record: outputs