defaults:
  - _self_

hate:
  _target_: buttermilk.runner.flow.Flow
  source: hate development
  steps:
    - name: describer
      _target_: buttermilk.agents.describer.Describer
      num_runs: 1
      parameters: 
        template: describe
        model:
          - gemini15pro
      inputs:
        record: record

    - _target_: buttermilk.agents.lc.LC
      name: judger
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: judge
        criteria: 
          - criteria_ordinary
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
      outputs:
        answers:
          - job_id: job_id
            flow_id: flow_id
            model: parameters.model
            criteria: parameters.criteria
            template: parameters.template
            reasons: outputs.reasons

    - _target_: buttermilk.agents.lc.LC
      name: synth
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: synthesise
        instructions: judge
        criteria: criteria_ordinary
        formatting: json_rules
        model: ${llm}
      inputs:
        content: record.text
        record: record
        answers: judger.answers
      outputs:
        answers:
          - job_id: job_id
            flow_id: flow_id
            model: parameters.model
            criteria: parameters.criteria
            template: parameters.template
            reasons: outputs.reasons

    - _target_: buttermilk.agents.lc.LC
      name: eval
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: differences
        criteria: criteria_ordinary
        model: ${llm}
      inputs:
        content: record.text
        answers:
          - judger.answers
          - synth.answers
      outputs:
        differences: outputs.reasons
        model: parameters.model
        criteria: parameters.criteria
        template: parameters.template

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      convert_json_columns:
        - answers
        - synthesis
        - differences
      save:
        type: gsheets
        sheet_id: null
        sheet_name: evals
        title: Hatespeech flow
      inputs:
        flow_id: flow_id
        record_id: record.record_id
        job_id: job_id
        timestamp: timestamp
        record: record
        zeroshot: judger.answers
        synthesis: synth.answers
        differences: eval.differences