hate:
  _target_: buttermilk.runner.creek.Creek
  source: hate development
  steps:
    - _target_: buttermilk.agents.lc.LC
      name: judger
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: judge
        criteria: 
          - criteria_ordinary
        formatting: json_rules
        model:
          # - haiku
          - gpt4o
          - llama31_70b
          - sonnet
          - gemini15pro 
      inputs:
        record: record
      outputs:
        answers:
          job_id: job_id
          model: parameters.model
          criteria: agent_info.parameters.criteria
          template: agent_info.parameters.template
          reasons: outputs.reasons
    - _target_: buttermilk.agents.lc.LC
      name: synth
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: synthesise
        instructions: judge
        criteria: criteria_ordinary
        formatting: json_rules
        model:
          # - haiku
          - gpt4o
          - sonnet
      inputs:
        content: record.text
        record: record
        answers: judger.answers
      outputs:
        answers:
          job_id: job_id
          model: parameters.model
          criteria: agent_info.parameters.criteria
          template: agent_info.parameters.template
          reasons: outputs.reasons

    - _target_: buttermilk.agents.lc.LC
      name: eval
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: differences
        criteria: criteria_ordinary
        model:
          # - haiku
          - gpt4o
          - sonnet
      inputs:
        content: record.text
        answers:
          - judger.answers
          - synth.answers
      outputs:
          analysis: outputs.analysis
          model: parameters.model
          timestamp: timestamp
          job_id: job_id
          record_id: record.record_id