hate:
  _target_: buttermilk.runner.creek.Creek
  source: hate development
  steps:
    - _target_: buttermilk.agents.lc.LC
      name: judger
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: judge
        criteria: 
          - criteria_ordinary
        formatting: json_rules
        model:
          # - haiku
          - gpt4o
          - llama31_70b
          - sonnet
          - gemini15pro 
      inputs:
        record: record
      outputs:
        job_id: job_id
        model: parameters.model
        criteria: parameters.criteria
        template: parameters.template
        reasons: outputs.reasons

    - _target_: buttermilk.agents.lc.LC
      name: synth
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: synthesise
        instructions: judge
        criteria: criteria_ordinary
        formatting: json_rules
        model:
          # - haiku
          - gpt4o
          - sonnet
      inputs:
        content: record.text
        record: record
        answers:
          - job_id: judger.job_id
            model: judger.model
            criteria: judger.criteria
            template: judger.template
            reasons: judger.reasons
      outputs:
        job_id: job_id
        model: parameters.model
        criteria: parameters.criteria
        template: parameters.template
        reasons: outputs.reasons

    - _target_: buttermilk.agents.lc.LC
      name: eval
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: differences
        criteria: criteria_ordinary
        model:
          # - haiku
          - gpt4o
          - sonnet
      inputs:
        content: record.text
        answers:
          - job_id: judger.job_id
            model: judger.model
            criteria: judger.criteria
            template: judger.template
            reasons: judger.reasons
          - job_id: synth.job_id
            model: synth.model
            criteria: synth.criteria
            template: synth.template
            reasons: synth.reasons
      outputs:
          reasons: outputs.reasons
          model: parameters.model
          timestamp: timestamp
          job_id: job_id
          flow_id: flow_id
          record_id: record.record_id

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      convert_json_columns:
        - answers
        - synthesis
        - differences
        - analysis
      save:
        type: gsheets
        sheet_id: null
        sheet_name: evals
        title: Hatespeech flow
      inputs:
        flow_id: flow_id
        record_id: record.record_id
        job_id: job_id
        timestamp: timestamp
        models:
          - judger.model
          - synth.model
          - eval.model
        criteria: 
          - judger.criteria
          - synth.criteria
        template: 
          - judger.template
          - synth.template
        record: record
        answers:  judger.reasons
        synthesis: synth.reasons
        differences: eval.reasons
        eval_model: eval.model
