# defaults:
#   - _self_

moa:
  _target_: buttermilk.runner.moa.MoA
  source: trans journalists guidelines assessment
  save: ${save}

  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index:
        - record_id

  steps:
    # - name: describer
    #   num_runs: 1
    #   variants:
    #     template: describe
    #     download_if_necessary: true
    #     model:
    #       - gemini2pro

    - name: context_owl
      description: Spots little things that are easy to miss.
      agent: LLMAgent
      num_runs: 1
      save: ${save}
      variants:
        template: owl
        model: ${llms.general}
      inputs:
        record: record
    - name: judge
      description: Applies criteria to content.
      agent: LLMAgent
      num_runs: 1
      save: ${save}
      variants:
        template: judge
        model: ${llms.general}
        formatting: json_rules
        criteria:
          - criteria_ordinary
      inputs:
        record: record
        feedback: context_owl
    - name: synth
      agent: LLMAgent
      description: Synthesizes draft answers.
      num_runs: 1
      save: ${save}
      variants:
        model: ${llms.synthesisers}
        template: synthesise_judger
        instructions: >
          Carefully apply EACH of the CRITERIA in order and provide a COMPLETE and SPECIFIC explanation about whether the particular rule has been violated and how. Use quotes from the content where necessary to support your analysis.
        criteria: criteria_ordinary
        formatting: json_rules
      inputs:
        record: record
        answers: judge
        feedback: context_owl
    # - name: eval
    #   num_runs: 1
    #   save: ${save}
    #   variants:
    #     template: differences
    #     criteria: >
    #       Evaluate how well the provided content aligns with journalistic standards
    #       and best practices for reporting on stories related to trans people.
