# defaults:
#   - _self_

moa:
  _target_: buttermilk.runner.moa.MoA
  source: trans journalists guidelines assessment
  save: ${save}
  llms: ${llms.general}

  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index:
        - record_id

  steps:
    # - name: describer
    #   num_runs: 1
    #   parameters:
    #     template: describe
    #     download_if_necessary: true
    #     model:
    #       - gemini2pro
    - name: judge
      num_runs: 1
      save: ${save}
      parameters:
        template: judge
        criteria:
          - criteria_ordinary
          - criteria_simple
        formatting: json_rules
        model: ${llms.judgers}
      inputs:
        - record
    # - name: context_owl
    #   num_runs: 1
    #   save: ${save}
    #   parameters:
    #     template: owl
    #     model: ${llms.general}
    - name: synth
      num_runs: 1
      save: ${save}
      parameters:
        template: synthesise_judger
        instructions: judge
        criteria: criteria_simple
        formatting: json_rules
        model: ${llms.synthesisers}
      inputs:
        - record
        - judge
        - context_owl
    # - name: eval
    #   num_runs: 1
    #   save: ${save}
    #   parameters:
    #     template: differences
    #     criteria: >
    #       Evaluate how well the provided content aligns with journalistic standards
    #       and best practices for reporting on stories related to trans people.
