defaults:
  - _self_
  - /data: osb_vector
  - /agents@osb.agents.rag_agent: rag_generic
  - /agents@osb.observers.host_ra: host/ra

osb:
  _target_: buttermilk.runner.flow.Flow
  source: api development
  orchestrator: buttermilk.orchestrators.groupchat.AutogenOrchestrator
  description: OSB Research Assistant - Interactive RAG agent for Online Safety Bureau cases
  parameters: {}
  agents:
    search:
      _target_: LLMAgent
      num_runs: 1
      parameters: 
        template: osb
        formatting: json
      variants:
        model: ${llm}
      data: osbcasessummary

    synth:
      _target_: LLMAgent
      num_runs: 1
      concurrency: 20
      parameters:
        template: synthesise
        formatting: json
      variants:
        model: ${llm}
      inputs:
        answers: search
        
  storage:
    osbcasessummary:
      type: vector
      uri: gs://prosocial-public/osb/03_osb_fulltext_summaries.json
      db:
        type: chromadb
        embeddings: gs://prosocial-public/osb/04_osb_embeddings_vertex-005.json
        model: text-embedding-005
        store: ".chromadb"
