
defaults:
  - _self_

osb:
  _target_: buttermilk.runner.creek.Creek
  source: api development
  steps:
    - name: search
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 2
      save: ${save}
      parameters: 
        template: osb
        model:
          - gemini15pro
          - gpt4o
        dataset: osbcasessummary
  data:
    - name: osbcasesfull
      type: file
      uri: gs://dmrc-platforms/data/osb/01_osb_cases.json
    - name: osbcasessummary
      type: bq
      dataset: dmrc-platforms.osb.case_summaries
      columns:
        record_id: record_id
        title: title
        content: content
        reasons: reasons
        standards: standards
        topics: topics
        recommendations: recommendations