
defaults:
  - _self_

osb:
  _target_: buttermilk.runner.flow.Flow
  source: api development
  steps:
    - name: search
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters: 
        template: osb
        formatting: json
        model: ${llm}
        dataset: osbcasessummary
      inputs:
        record: record
        content: record.text

    - _target_: buttermilk.agents.lc.LC
      name: synth
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: synthesise
        formatting: json
        model: ${llm}
      inputs:
        answers: search.outputs
        
  data:
    - name: cases
      type: vector
      uri: gs://prosocial-public/osb/03_osb_fulltext_summaries.json
      db:
        type: chromadb
        embeddings: gs://prosocial-public/osb/04_osb_embeddings_vertex-005.json
        model: text-embedding-005
        store: ".chromadb"

