
defaults:
  - _self_

osb:
  _target_: buttermilk.runner.flow.Flow
  source: api development
  steps:
    - name: search
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters: 
        template: osb
        model: ${llm}
        dataset: osbcasessummary

    - _target_: buttermilk.agents.lc.LC
      name: synth
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: synthesise
        instructions: osb
        model: ${llm}
      inputs:
        answers:
          - job_id: search.job_id
            model: search.outputs.model
            reasons: search.outputs.reasons
      outputs:
        job_id: job_id
        model: parameters.model
        criteria: parameters.criteria
        template: parameters.template
        reasons: outputs.reasons
  data:
    - name: osbcasessummary
      type: file
      uri: gs://prosocial-public/osb/02_osb_summaries_20241120.jsonl