
defaults:
  - _self_

osb:
  _target_: buttermilk.runner.flow.Flow
  source: api development
  steps:
    - name: search
      _target_: LLMAgent
      num_runs: 1
      parameters: 
        template: osb
        formatting: json
      variants:
        model: ${llm}
      data: osbcasessummary

    - name: synth
      _target_: LLMAgent
      num_runs: 1
      concurrency: 20
      parameters:
        template: synthesise
        formatting: json
      variants:
        model: ${llm}
      inputs:
        answers: search
        
  data:
    cases:
      type: vector
      uri: gs://prosocial-public/osb/03_osb_fulltext_summaries.json
      db:
        type: chromadb
        embeddings: gs://prosocial-public/osb/04_osb_embeddings_vertex-005.json
        model: text-embedding-005
        store: ".chromadb"

