defaults:
  - _self_
  - criteria@panel.params.criteria: trans
  - agents@panel.agents:
      - manager
      - host
      - judge
      - owl

panel:
  _target_: buttermilk.runner.groupchat.AutogenOrchestrator
  description: Panel of Agents directed chat
  name: trans
  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index:
        - record_id
  params:
    criteria: replace
    task: >
      The purpose of this conversation is to assess a single piece of content. You are the HOST.
      Unless the MANAGER directs you otherwise, the standard approach is for you to:
        1. Ask the JUDGEs to provide an initial review of the content.
        2. Identify areas of consensus and disagreement.
        3. FOR EACH area of disagreement, ask the JUDGEs to refine their answer, taking uncertainty and other perspectives into account.
        4. REPEAT STEP 3 until all areas of disagreement have been resolved or an impasse has been reached.
        5. Once all areas of disagreement have been resolved, ask the JUDGEs to each synthesize a final answer.
        6. Ask all JUDGEs to vote on their preferred answers.
        7. Present the best draft answer to the MANAGER for approval.

# You are the HOST of a conference table, helping the MANAGER facilitate a discussion and driving towards a consensus-based answer. Make sure the discussion progresses, try to avoid going in circles, and try to clarify areas of disagreement to focus on one at a time.
