defaults:
  - _self_
  - criteria@panel.parameters.criteria: trans
  - agents@panel.agents:
      - manager
      - fetch
      - host
      - judge
      - owl

panel:
  _target_: buttermilk.runner.selector.Selector
  description: Panel of Agents directed chat
  name: trans
  data:
    tja_train:
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index:
        - record_id
  parameters:
    criteria: replace

# You are the HOST of a conference table, helping the MANAGER facilitate a discussion and driving towards a consensus-based answer. Make sure the discussion progresses, try to avoid going in circles, and try to clarify areas of disagreement to focus on one at a time.
