defaults:
  - criteria@simple.parameters.criteria: trans
  - datasets@simple.datasets: tja_train   
  - agents@simple.agents:
      - host
      - judge
      - scorer
  - _self_


simple:  
  _target_: buttermilk.runner.selector.SelectorOrchestrator
  record:
  parameters:
    criteria: ${criteria}