simple:
  _target_: buttermilk.runner.flow.Flow
  source: hate development
  steps:
    # - name: describer
    #   _target_: buttermilk.agents.describer.Describer
    #   parameters: 
    #     template: describe
    #     model:
    #       - gemini15pro
    #   inputs:
    #     record: record
    #   outputs:
    #     name: title
    #     description: description
    #     caption: caption
    #     transcript: transcript
    - _target_: buttermilk.agents.lc.LC
      name: judger
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: judge
        criteria: criteria_ordinary
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
      outputs:
          job_id: job_id
          model: parameters.model
          criteria: parameters.criteria
          template: parameters.template
          reasons: outputs.reasons

