simple:
  _target_: buttermilk.runner.moa.MoA
  source: development flow


  steps:
    - name: fetch
      agent: Fetch
      description: fetch urls and stored records for the chat
      inputs:
        prompt: q

    - name: judge
      description: Applies criteria to content.
      agent: LLMAgent
      num_runs: 2
      variants:
        template: judge
        criteria:
          - criteria_ordinary
        formatting: json_rules
        model: gemini2flashthinking
      inputs:
        record: record

    - name: feedback
      description: QA for mistakes.
      agent: LLMAgent
      num_runs: 1
      save: ${save}
      variants:
        template: feedback
        model: ${llms.general}
      inputs:
        history: history

    - name: synth
      agent: LLMAgent
      description: Synthesizes draft answers.
      num_runs: 1
      save: ${save}
      variants:
        model: gemini2flashthinking
        template: synthesise_judger
        instructions: >
          Carefully apply EACH of the CRITERIA in order and provide a COMPLETE and SPECIFIC explanation about whether the particular rule has been violated and how. Use quotes from the content where necessary to support your analysis.
        criteria: criteria_ordinary
        formatting: json_rules
      inputs:
        content: record.fulltext
        answers: judge
        feedback: feedback

    - name: eval
      agent: LLMAgent
      num_runs: 1
      description: show differences between answers
      variants:
        template: differences
        criteria: >
          Evaluate how well the provided content aligns with the rules.
        model: gemini2flashthinking
      inputs:
        content: record.fulltext
        answers:
          - judge
          - synth
        feedback: feedback
