simple:
  _target_: buttermilk.runner.creek.Creek
  source: hate development
  steps:
    - _target_: buttermilk.agents.lc.LC
      name: judger
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: judge
        criteria: criteria_ordinary
        formatting: json_rules
        model:
          - haiku
      inputs:
        record: record
      outputs:
        answers:
          job_id: job_id
          model: parameters.model
          criteria: agent_info.parameters.criteria
          template: agent_info.parameters.template
          reasons: outputs.reasons

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      save:
        type: gsheets
        sheet_name: evals
        title: Trans Guidelines Judger
      inputs:
        job_id: judger.job_id
        timestamp: timestamp
        record: record
        answers: judger.answers
        model: judger.answers.model
        criteria: judger.answers.criteria
        template: judger.answers.template
        reasons: judger.answers.reasons
