defaults:
  - _self_
  - criteria@structured_debate.parameters.criteria: trans
  - agents@structured_debate.agents:
      - manager
      - fetch
      - host
      - judge
      - synthesiser

structured_debate:
  _target_: buttermilk.runner.selector.Selector
  description: Structured multi-stage debate with user interaction
  name: structured_debate
  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index:
        - record_id
  parameters:
    criteria: replace
    task: >
      The purpose of this conversation is to conduct a structured, multi-stage debate to assess content deeply.
  agents:
    host:
      parameters:
        template: structured_debate_conductor
