
# defaults:
  # - save: /save/bq.yaml
  
summarise_osb:
  _target_: buttermilk.runner.creek.Creek
  source: osb development
  steps:
    - name: summarise
      _target_: buttermilk.agents.lc.LC
      num_runs: 2
      concurrency: 20
      save: ${save}
      parameters: 
        template: summarise
        instructions: summarise_osb
        model:
          - gpt4o
          - sonnet
          - gemini15pro

    - name: synthesise
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters: 
        template: synthesise
        instructions: summarise_osb
        model:
          - gpt4o
          - sonnet
        content: record.text
        answers: summarise
     