# defaults:
#   - _self_

trans:
  _target_: buttermilk.runner.flow.Flow
  source: trans journalists guidelines assessment
  save: ${save}

  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index:
        - record_id

  steps:
    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 2
      save: ${save}
      parameters:
        template: judge
        criteria:
          - trans_simplified
          - cte
          - tja
          - glaad
          - hrc
          - trans_factored
        formatting: json_rules
        model: ${llms.judgers}
      outputs:
        identifier: identifier
        params:
          job_id: job_id
          template: parameters.template
          criteria: parameters.criteria
          instructions: parameters.instructions
          model: parameters.model
        answer: outputs

    - name: context_owl
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: owl
        model: ${llms.general}

    - name: synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: synthesise_judger
        instructions: judge
        criteria: trans_simplified
        formatting: json_rules
        model: ${llms.synthesisers}
      inputs:
        answers: judger
        feedback: context_owl.intervention
      outputs:
        identifier: identifier
        params:
          job_id: job_id
          template: parameters.template
          criteria: parameters.criteria
          instructions: parameters.instructions
          model: parameters.model
        answer: outputs

    - name: scorer
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: evaluate
        model: ${llms.synthesisers}
        answer:
          - judger
          - synth
      inputs:
        instructions: >
          The analyst was tasked with evaluating how well the provided content 
          aligned with journalistic standards and best practices for reporting
          on stories related to trans people.
        expected: record.ground_truth

    - name: eval
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: differences
        criteria: >
          Evaluate how well the provided content aligns with journalistic standards
          and best practices for reporting on stories related to trans people.
        model: ${llms.synthesisers}
      inputs:
        content: record.fulltext
        answers:
          - judger
          - synth
