# defaults:
#   - _self_

trans_score:
  _target_: buttermilk.runner.flow.Flow
  source: api development
  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index: 
        - record_id
  
  steps:
    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 2
      save: ${save}
      data:
        - name: judger
          type: outputs
          join:
            record_id: record_id
          index:
            - record_id
            - judger.job_id
      parameters: 
        template: judge
        criteria: 
          - trans_cte
          - trans_tja
          - trans_glaad
          - trans_hrc
          - trans_simplified
          - trans_factored
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
      outputs:
        identifier: identifier
        record_id: record.record_id
        job_id: job_id
        result: answer
      
    - name: scorer
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      data:
        - name: scorer
          type: outputs
          join:
            record_id: record.record_id
          index:
            - record.record_id
            - judger.job_id
            - scorer.job_id

      parameters:
        template: evaluate
        model: ${llm}
        answer: judger.answer
        expected: record.ground_truth
      outputs:
        answer:
          - answer_id: judger.job_id
            answer: judger.answer
            judge_llm: judger.parameters.model
            criteria: judger.criteria
        evaluation:
          job_id: scorer.job_id
          score: outputs.score
          score_llm: scorer.parameters.model
          reasons: outputs.reasons
          groundtruth: record.ground_truth

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      convert_json_columns:
        - content
        - answer
        - evaluation
      save:
        type: gsheets
        sheet_name: scores
        title: Trans Guidelines Scorer
      inputs:
        flow_id: flow_id
        job_id: job_id
        record_id: record.record_id
        timestamp: timestamp
        judger_llm: judger.model
        template: judger.template
        criteria: judger.criteria
        scorer_llm: scorer.model
        record: record.text
        groundtruth: record.ground_truth
        content: 
          - scorer.content
        answer: 
          - scorer.answer
        evaluation: scorer.evaluation
        eval_reasons: scorer.evaluation.reasons
        eval_score: scorer.evaluation.score
