# defaults:
#   - _self_

trans:
  _target_: buttermilk.runner.flow.Flow
  source: trans journalists guidelines assessment
  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index: 
        - record_id

  steps: 
    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 3
      save: ${save}
      parameters: 
        template: judge
        criteria: 
          - cte
          - tja
          - glaad
          - hrc
          - trans_simplified
          - trans_factored
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
      outputs:
        identifier: identifier
        record_id: record.record_id
        job_id: job_id
        answer: result
        model: parameters.model
        criteria: parameters.criteria
        template: parameters.template
      
    - name: synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: synthesise_judger
        instructions: judge
        criteria: trans_simplified
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
        answers: judger.outputs
      outputs:
        identifier: identifier
        record_id: record.record_id
        job_id: job_id
        answer: result
        model: parameters.model
        criteria: parameters.criteria
        template: parameters.template
    
    - name: scorer
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: evaluate
        model: ${llm}
        answer:
          - judger.answer
          - synth.answer
        expected: record.ground_truth
      outputs:
        job_id: scorer.job_id
        score: outputs.score
        score_llm: scorer.parameters.model
        reasons: outputs.reasons
        
    - name: eval 
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: differences
        criteria: 
          - trans_simplified
        model: ${llm}
      inputs:
        content: record.text
        answers:
          - judger.answers
          - synth.answers
      outputs:
        differences: result
        judge: inputs.answers.model
        criteria: input.answers.criteria
        template: input.answers.template

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      convert_json_columns:
        - answers
        - synthesis
        - differences
        - analysis
      save:
        type: gsheets
        sheet_id: 1e5pun-ry8iZgiUSNtGlwWPW3rD8DxcODNOVrnnyRbe4
        sheet_name: evals
        title: Trans Guidelines Judger
      inputs:
        flow_id: flow_id
        job_id: job_id
        timestamp: timestamp
        models:
          - judger.model
          - synth.model
          - eval.model
        criteria: 
          - judger.criteria
          - synth.criteria
        template: 
          - judger.template
          - synth.template
        record: record
        answers:
          - judger.answers
        synthesis:
          - synth.answers
        differences:
          - differences: eval.differences
            model: eval.model
