# defaults:
#   - _self_

trans:
  _target_: buttermilk.runner.flow.Flow
  source: trans journalists guidelines assessment
  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index: 
        - record_id

  steps:
    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters: 
        template: judge
        criteria:
          - trans_simplified
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
      outputs:
        answer:
          - job_id: job_id
            reasons: outputs.reasons
            prediction: outputs.prediction
            confidence: outputs.confidence
            severity: outputs.severity
            labels: outputs.labels

    # - name: context
    #   _target_: buttermilk.agents.lc.LC
    #   num_runs: 1
    #   save: ${save}
    #   parameters: 
    #     template: context
    #     model: ${llm}
    #   inputs:
    #     record: record
    #   outputs:
    #     feedback:
    #       text: outputs.description
    #       id: identifier

    - name: synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: synthesise_judger
        instructions: judge
        criteria: trans_simplified
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
        answers: judger.answer
        # feedback: context.feedback
      outputs:
        answer:
          - job_id: job_id
            reasons: outputs.reasons
            prediction: outputs.prediction
            confidence: outputs.confidence
            severity: outputs.severity
            labels: outputs.labels
    
    - name: scorer
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: evaluate
        model: ${llm}
        answer:
          - judger.outputs.answer
          - synth.outputs.answer
        expected: record.ground_truth
      inputs:
        instructions: |
            The analyst was tasked with evaluating how well the provided content 
            aligned with journalistic standards and best practices for reporting
            on stories related to trans people.
      outputs:
        score: outputs.score
        reasons: outputs.reasons
        
    - name: eval 
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: differences
        criteria: 
          - trans_simplified
        model: ${llm}
      inputs:
        content: record.text
        answers:
          - judger.outputs.answer
          - synth.outputs.answer
      outputs:
        differences: outputs
        judge: inputs.answers.model
        criteria: input.answers.criteria
        template: input.answers.template
