# defaults:
#   - _self_

trans:
  _target_: buttermilk.runner.creek.Creek
  source: api development
  steps: 
    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters: 
        template: judge
        criteria: 
          - trans_cte
          - trans_tja
          - trans_glaad
          - trans_hrc
          - trans_simplified
          - trans_factored
        formatting: json_rules
        model:
          - gpt4o
          - sonnet
          - gemini15pro
          - llama32_90b
      inputs:
        record: record
      outputs:
        answers:
          job_id: job_id
          model: parameters.model
          criteria: parameters.criteria
          template: parameters.template
          reasons: outputs.reasons
      
    - name: synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: synthesise
        instructions: judge
        criteria: trans_simplified
        formatting: json_rules
        model:
          - gpt4o
          - sonnet
      inputs:
        content: record
        answers:
          - judger.answers
      outputs:
        answers:
          job_id: job_id
          model: parameters.model
          criteria: parameters.criteria
          template: parameters.template
          reasons: outputs.reasons
    
    - name: eval 
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: differences
        criteria: 
          - trans_simplified
        model:
          - gpt4o
          - sonnet
      inputs:
        content: record
        answers:
          - judger.answers
          - synth.answers
      outputs:
          analysis: outputs.reasons
          model: parameters.model
          timestamp: timestamp
          job_id: job_id
          record_id: record.record_id

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      save:
        type: gsheet
      parameters:
        sheet_name: evals
        title: Trans Guidelines Judger
      inputs:
        job_id: job_id
        timestamp: timestamp
        record: record
        answers: judger.answers
        synthesis: synth.answers
        differences: eval.analysis
        model: eval.model
