# defaults:
#   - _self_

trans:
  _target_: buttermilk.runner.creek.Creek
  source: api development
  steps:
    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters: 
        template: judge
        criteria: 
          - trans_cte
          - trans_tja
          - trans_glaad
          - trans_hrc
          - trans_simplified
          - trans_factored
        formatting: json_rules
        model:
          - gpt4o
          - sonnet
      inputs:
        record: record
        record_id: record.record_id
        content: record.text
        title: record.title
      outputs:
        answers:
          job_id: job_id
          model: parameters.model
          criteria: agent_info.parameters.criteria
          template: agent_info.parameters.template
          reasons: outputs.reasons
      
    - name: synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      parameters:
        template: synthesise
        instructions: judge
        criteria: trans_simplified
        formatting: json_rules
        model:
          - gpt4o
          - sonnet
      inputs:
        record: record
        content: record.text
        answers:
          - judger.answers
      outputs:
        answers:
          job_id: job_id
          model: parameters.model
          criteria: agent_info.parameters.criteria
          template: agent_info.parameters.template
          reasons: outputs.reasons
      
    
    - name: eval 
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      parameters:
        template: differences
        criteria: 
          - trans_simplified
        model:
          - gpt4o
          - sonnet
      inputs:
        content: record.text
        answers:
          - judger.answers
          - synth.answers
      outputs:
          analysis: outputs.analysis
          model: parameters.model
          timestamp: timestamp
          job_id: job_id
          record_id: record.record_id