# defaults:
#   - _self_

trans:
  _target_: buttermilk.runner.flow.Flow
  source: trans journalists guidelines assessment
  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index: 
        - record_id

  steps:
    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters: 
        template: judge
        criteria:
          - trans_factored
          - trans_simplified
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
      outputs:
        answer:
          identifier: identifier
          record_id: record.record_id
          job_id: job_id
          result: outputs
          model: parameters.model
          criteria: parameters.criteria
          template: parameters.template
    - name: context
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters: 
        template: context
        model: ${llm}
      inputs:
        record: record
      outputs:
        feedback:
          text: outputs.description
          id: identifier

    - name: synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: synthesise_judger
        instructions: judge
        criteria: trans_simplified
        formatting: json_rules
        model: ${llm}
      inputs:
        record: record
        answers: judger.answer
        feedback: context.feedback
      outputs:
        answer:
          identifier: identifier
          record_id: record.record_id
          job_id: job_id
          result: outputs
          model: parameters.model
          criteria: parameters.criteria
          template: parameters.template
    
    - name: scorer
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: evaluate
        model: ${llm}
        answers:
          - judger.outputs.answer
          - synth.outputs.answer
        expected: record.ground_truth
      outputs:
        score: outputs.score
        reasons: outputs.reasons
        
    - name: eval 
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: differences
        criteria: 
          - trans_simplified
        model: ${llm}
      inputs:
        content: record.text
        answers:
          - judger.outputs.answer
          - synth.outputs.answer
      outputs:
        differences: outputs
        judge: inputs.answers.model
        criteria: input.answers.criteria
        template: input.answers.template

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      convert_json_columns:
        - params
        - analysis
      save:
        type: gsheets
        sheet_name: evals
        title: Trans Guidelines Judger
