# defaults:
#   - _self_

trans:
  _target_: buttermilk.runner.creek.Creek
  source: api development
  steps: 
    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters: 
        template: judge
        criteria: 
          - trans_cte
          - trans_tja
          - trans_glaad
          - trans_hrc
          - trans_simplified
          - trans_factored
        formatting: json_rules
        model:
          - gpt4o
          - sonnet
          - gemini15pro
          - llama32_90b
      inputs:
        record: record
      outputs:
        job_id: job_id
        flow_id: flow_id
        model: parameters.model
        criteria: parameters.criteria
        template: parameters.template
        reasons: outputs.reasons
      
    - name: synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: synthesise
        instructions: judge
        criteria: trans_simplified
        formatting: json_rules
        model:
          - gpt4o
          - sonnet
      inputs:
        content: record
        answers:
          - job_id: judger.job_id
            model: judger.parameters.model
            criteria: judger.parameters.criteria
            template: judger.parameters.template
            reasons: judger.outputs.reasons
      outputs:
        job_id: job_id
        flow_id: flow_id
        model: parameters.model
        criteria: parameters.criteria
        template: parameters.template
        reasons: outputs.reasons
    
    - name: eval 
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      concurrency: 20
      save: ${save}
      parameters:
        template: differences
        criteria: 
          - trans_simplified
        model:
          - gpt4o
          - sonnet
      inputs:
        content: record
        answers:
          - job_id: judger.job_id
            model: judger.parameters.model
            criteria: judger.parameters.criteria
            template: judger.parameters.template
            reasons: judger.reasons
          - job_id: synth.job_id
            model: synth.parameters.model
            criteria: synth.parameters.criteria
            template: synth.parameters.template
            reasons: synth.reasons
      outputs:
          analysis: outputs.reasons
          model: parameters.model
          timestamp: timestamp
          job_id: job_id
          record_id: record.record_id

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      convert_json_columns:
        - answers
        - synthesis
        - differences
        - analysis
      save:
        type: gsheets
        sheet_id: 1e5pun-ry8iZgiUSNtGlwWPW3rD8DxcODNOVrnnyRbe4
        sheet_name: evals
        title: Trans Guidelines Judger
      inputs:
        models:
          - judger.model
          - synth.model
          - eval.model
        criteria: 
          - judger.criteria
          - synth.criteria
        template: 
          - judger.template
          - synth.template
        record: record
        answers: judger.reasons
        synthesis: synth.reasons
        differences: eval.analysis
        eval_model: eval.model
