# defaults:
#   - _self_

trans:
  _target_: buttermilk.runner.flow.Flow
  source: trans journalists guidelines assessment
  data:
    - name: tja_train
      type: file
      path: gs://prosocial-dev/data/tja_train.jsonl
      index: 
        - record_id

  steps:

    - name: judger
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters: 
        template: judge
        criteria:
          - trans_simplified
          - cte
          - tja
          - glaad
          - hrc
          - trans_factored
        formatting: json_rules
        model: ${llms.fast_judgers}
      inputs:
        record: record
      outputs:
        job_id: job_id
        identifier: identifier
        result:
          reasons: outputs.reasons
          prediction: outputs.prediction
          confidence: outputs.confidence
          severity: outputs.severity
          labels: outputs.labels

    - name: context_owl
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters: 
        template: owl
        model: o3-mini-high
      inputs:
        record: record
      outputs:
        intervention: outputs.intervention
        identifier: identifier

    - name: synth
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: synthesise_judger
        instructions: judge
        criteria: trans_simplified
        formatting: json_rules
        model: ${llms.synthesisers}
      inputs:
        record: record
        answers: judger
        feedback: context_owl.intervention
      outputs:
        job_id: job_id
        identifier: identifier
        result:
          reasons: outputs.reasons
          prediction: outputs.prediction
          confidence: outputs.confidence
          severity: outputs.severity
          labels: outputs.labels
    
    - name: scorer
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: evaluate
        model: ${llms.synthesisers}
        answer:
          - judger
          - synth
        expected: record.ground_truth
      inputs:
        instructions: |
            The analyst was tasked with evaluating how well the provided content 
            aligned with journalistic standards and best practices for reporting
            on stories related to trans people.
      outputs:
        identifier: inputs.answers.identifier
        score: outputs.score
        reasons: outputs.reasons
        
    - name: eval 
      _target_: buttermilk.agents.lc.LC
      num_runs: 1
      save: ${save}
      parameters:
        template: differences
        criteria: 
          - trans_simplified
        model: ${llms.synthesisers}
      inputs:
        content: record.fulltext
        answers:
          - judger
          - synth
      outputs:
        differences: outputs
        jobs: inputs.answers.job_id
        identifiers: inputs.answers.identifier

    - name: export
      _target_: buttermilk.agents.sheetexporter.GSheetExporter
      convert_json_columns:
        - record
        - owl
        - reasons
        - differences
      save:
        type: gsheets
        sheet_id: null
        sheet_name: evals
        title: TJA Guidelines full flow
      inputs:
        flow_id: flow_id
        record_id: record.record_id
        job_id: job_id
        timestamp: timestamp
        record: record.fulltext
        owl: context_owl
        scores: scorer.score
        reasons: scorer
        # zeroshot: judger.answers
        # synthesis: synth.answers
        differences: eval.differences