[tool.poetry]
name = "buttermilk"
version = "0.1.0"
description = ""
authors = ["Nicolas Suzor <nic@suzor.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
shortuuid = "^1.0.13"
psutil = "^6.0.0"
azureml-fsspec = "^1.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
