[tool.poetry]
name = "buttermilk"
version = "0.1.0"
description = ""
authors = ["Nicolas Suzor <nic@suzor.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
shortuuid = "^1.0.13"
psutil = "^6.0.0"
cloudpathlib = "^0.18.1"
fsspec = "^2024.6.1"
requests = "^2.32.3"
pathlib = "^1.0.1"
pyyaml = "^6.0.2"
urllib3 = "^2.2.2"
azureml-core = "^1.57.0"
azure-identity = "^1.17.1"
promptflow = {extras = ["core", "devkit", "azure"], version = "^1.15.0"}
hydra-core = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
