[tool.poetry]
name = "buttermilk"
version = "0.1.0"
description = ""
authors = ["Nicolas Suzor <nic@suzor.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
shortuuid = "^1.0.13"
psutil = "^6.0.0"
cloudpathlib = "^0.18.1"
fsspec = "^2024.6.1"
requests = "^2.32.3"
pathlib = "^1.0.1"
pyyaml = "^6.0.2"
urllib3 = "^2.2.2"
azureml-core = "^1.57.0"
azure-identity = "^1.17.1"
promptflow = {extras = ["core", "devkit", "azure"], version = "^1.15.0"}
hydra-core = "^1.3.2"
azure-keyvault = "^4.2.0"
pydantic = "^2.8.2"
langchain = "^0.2.14"
promptflow-tools = {git = "https://github.com/microsoft/promptflow.git", rev = "main", subdirectory = "src/promptflow-tools"}
langchain-prompty = "^0.0.2"
coloredlogs = "^15.0.1"
google-cloud-logging = "^3.11.2"
json-repair = "^0.28.3"
google-generativeai = "^0.7.2"
langchain-anthropic = "^0.1.23"
langchain-google-vertexai = "^1.0.10"
langchain-openai = "^0.1.22"
langchain-community = "^0.2.12"
langchain-google-genai = "^1.0.10"
langchain-together = "^0.1.5"
langchain-experimental = "^0.0.64"
gcsfs = "^2024.6.1"
azure-ai-ml = "1.18.0"
boto3 = "^1.35.7"
evaluate = "^0.4.2"
torch = "^2.4.0"
transformers = "^4.44.2"
azure-ai-contentsafety = "^1.0.0"
azure-cognitiveservices-vision-contentmoderator = "^1.0.0"
octoai = "^1.6.0"
unidecode = "^1.3.8"
accelerate = "^0.33.0"
huggingface-hub = {extras = ["hf-transfer"], version = "^0.24.6"}
peft = "^0.12.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
alt-pytest-asyncio = "^0.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
