defaults:
  - _self_

name: default_project
job: development
secret_provider:
logger: 
verbose: true
tracing: true
models_secret: models
concurrent: 10

gcp:
  project: 
  region: 
  bucket: 
azure:
  vault: 
  resource_group: 
aws:
  secret_name: 
  region:

save:
  type: 
  destination:
  schema: 

data:
