defaults:
  - _self_
  - local
  - run: cli
  - llms: lite

# reduce path-induced surprises
hydra.job.chdir: false

verbose: false
flows: {}

bm:
  _target_: buttermilk._core.bm_init.BM
  session_info:
    name: ${run.name}
    job: ${run.job}

infrastructure:
  llms: {}
  
  # Default tracing configuration for non-cloud tracing providers
  tracing:
    weave: 
      enabled: true
    traceloop:
      enabled: false