name: default_project
job: development
secret_provider: azure
logger: gcp
verbose: true
models_secret: models
concurrent: 10
gcp:
  project: dmrc-platforms
  region: us-central1
  bucket: dmrc-analysis
azure:
  vault: https://suzorvault.vault.azure.net/
  resource_group: rg-suzor_ai
aws:
  secret_name: secret
  region: us-east-1
save:
  type: bq
  destination: dmrc-analysis.toxicity.flow
  schema: buttermilk/schemas/flow.json

data:
  runs:
    type: job
    name: runs
    dataset: dmrc-analysis.toxicity.flow
    last_n_days: 7
    aggregate: false
    max_records_per_group: 1
    filter:
    group:
      record_id: record.record_id
      job_id: job_id
    columns:
      timestamp: timestamp
      agent: agent_info.agent
      source: source
      record_id: record.record_id
      error: error
      parameters: parameters
