defaults:
  - run: cli
  - _self_
# reduce path-induced surprises
hydra.job.chdir: false
project_name: buttermilk
verbose: false
storage:
  traces:
    type: bigquery
    project_id: prosocial-443205
    dataset_id: testing
    table_id: traces
    dataset_name: traces
    schema_path: traces.schema.json
session:
  llm_wrapper: autogen
infrastructure:
  clouds:
    - type: gcp
      _target_: buttermilk._core.cloud_config.GCPConfig
      project_id: prosocial-443205
      region: us-central1
      location: us-central1
      storage_bucket: prosocial-dev
      secrets:
        _target_: buttermilk._core.cloud_config.SecretsServiceConfig
        models_secret: dev__llm__connections
        credentials_secret: dev__shared_credentials
      logging:
        _target_: buttermilk._core.cloud_config.LoggingServiceConfig
        enabled: true
        verbose: true
      pubsub:
        _target_: buttermilk._core.cloud_config.PubSubServiceConfig
        jobs_topic: jobs
        jobs_subscription: jobs-sub
        status_topic: flow
        status_subscription: flow-sub
      vertex:
        enabled: true
  # Unified tracing configuration for all tracing providers
  tracing:
    weave:
      enabled: false
      # project_id is WANDB_ENTITY for weave
      project_id: dmrc
    traceloop:
      enabled: false
      api_key:
      endpoint: https://api.traceloop.com
    otel:
      enabled: true
      endpoint: https://telemetry.googleapis.com
      otlp_headers: {}
  logging:
    type: gcp
    verbose: ${verbose}
    project_id: prosocial-443205
    location: us-central1
