defaults:
  - _self_
  - local
  - flows:
    - zot
    - trans
    - osb
  - llms: lite

verbose: true

bm:
  _target_: buttermilk._core.bm_init.BM
  session_info:
    name: buttermilk
    job: testing

infrastructure:
  clouds:
    - type: gcp
      _target_: buttermilk._core.cloud_config.GCPConfig
      project_id: prosocial-443205
      region: us-central1
      location: us-central1
      storage_bucket: prosocial-dev
      
run:
  mode: console
  ui: console
  human_in_loop: false
  name: buttermilk
  job: testing