# @package bm.infrastructure
# University research infrastructure configuration

clouds:
  - type: gcp
    project_id: ${oc.env:UNIVERSITY_GCP_PROJECT,university-research-001}
    region: us-west1
    storage_bucket: ${oc.env:RESEARCH_BUCKET,university-research-data}
    bigquery_dataset: research_datasets

secret_provider:
  type: gcp
  project_id: ${oc.env:UNIVERSITY_GCP_PROJECT,university-research-001}
  models_secret: research-llm-credentials
  credentials_secret: research-shared-credentials

logger_cfg:
  type: gcp
  project_id: ${oc.env:UNIVERSITY_GCP_PROJECT,university-research-001}
  location: us-west1
  verbose: false

run_info:
  platform: cloud
  save_dir_base: gs://${oc.env:RESEARCH_BUCKET,university-research-data}/results/

tracing:
  enabled: true
  provider: weave