defaults:
  - _self_
  - local

name: default_project
job: development
ui: console
bm:
  _target_: buttermilk.BM

  logger_cfg:
  clouds:
  tracing:
  run_info:
    name: ${name}
    job: ${job}
    platform: local
    max_concurrency: 16
    flow_api: http://flow:8000/flow/
    