defaults:
  - _self_
  - local
  - llms: lite
  - flows: []


ui: console

run:
  human_in_loop: true

bm:
  _target_: buttermilk._core.bm_init.BM
  logger_cfg:
  clouds:
  tracing:
    enabled: true
  
  name: ${name}
  job: ${job}
  platform: local
  flow_api: http://flow:8000/flow/
