defaults:
  - _self_
  - local
  - run: api
  # - defaults/data_source
  - llms: lite
  # - storage@bm.storage: []

bm:
  _target_: buttermilk._core.bm_init.BM
  name: ${run.name}
  job: ${run.job}
  platform:
  llms: ${llms}
