defaults:
  - _self_
  - local
  - llms: lite

name: default_project
job: development
ui: console

# launch params
uri:
flow:
record_id: 
prompt: 

bm:
  _target_: buttermilk.bm.BM

  logger_cfg:
  clouds:
  tracing:
    enabled: true
  run_info:
    name: ${name}
    job: ${job}
    platform: local
    max_concurrency: 16
    flow_api: http://flow:8000/flow/
    