defaults:
  - _self_
  - local


bm:
  _target_: buttermilk.BM
  cfg:
    name: default_project
    job: development
    secret_provider:
      type: azure
      vault: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      resource_group: 

    save_dest:
      type: gcp
      project: gcp_project_id
      region: us-central1
      bucket: bucket_name

    logger: 
      type: gcp
    verbose: true
    tracing: 
      enabled: true
    run:
      platform: local
      max_concurrency: 16
