defaults:
  - _self_
  - local
  - run: api
  - llms: lite

# reduce path-induced surprises
hydra.job.chdir: false

verbose: false
flows: {}

bm:
  _target_: buttermilk._core.bm_init.BM
  run_info:
    name: ${run.name}
    job: ${run.job}
  llms: ${llms}
  tracing:
    enabled: true