defaults:
  - _self_
  - local

name: default_project
job: development

bm:
  _target_: buttermilk.BM
  cfg:
    name: ${name}
    job: 
    logger:
    clouds:
    tracing:
    run:
      platform: local
      max_concurrency: 16
      flow_api: http://flow:8000/flow
      