defaults:
  - _self_
  - local
  - llm: lite

name: default_project
job: development

bm:
  _target_: buttermilk.BM
  cfg:
    name: ${name}
    job: ${job}

    clouds:
      - type: vertex
        project: gcp_project_id
        region: us-central1
        bucket: dmrc-analysis
          
    logger: 
      type: gcp
      verbose: false
    tracing: 
      enabled: true
      
    run:
      platform: local
      max_concurrency: 16
      flow_api: http://flow:8000/flow