defaults:
  - _self_
  - local


bm:
  _target_: buttermilk.BM
  cfg:
    name: default_project
    job: development

    save_dest:
      type: gcp
      project: gcp_project_id
      region: us-central1
      bucket: bucket_name

    clouds:
      - type: vertex
        project: gcp_project_id
        region: us-central1
        bucket: dmrc-analysis
          
    logger: 
      type: gcp
    verbose: true
    tracing: 
      enabled: false
      
    run:
      platform: local
      max_concurrency: 16
