defaults:
  - _self_
  - local


bm:
  _target_: buttermilk._core.bm_init.BM
  logger_cfg:
  clouds:
  tracing:
    enabled: true
  
  name: ${name}
  job: ${job}
  platform: local
  flow_api: http://flow:8000/flow/
