# @package __global__

defaults:
  - _self_
  - save: bq

bm:
  cfg:
    name: automod
    job: debugging
    logger: 
      type: gcp
    tracing: 
      enabled: true
    verbose: true
    save_dest:
      type: gcp
      project: dmrc-analysis
      region: us-central1
      bucket: dmrc-analysis
      
    secret_provider: 
      type: azure
      vault: https://suzorvault.vault.azure.net/
      resource_group: rg-suzor_ai
      models_secret: models

    pubsub:
      type: gcp
      project: dmrc-platforms
      subscription: flow-sub

    run:
      platform: local
      max_concurrency: 32