# @package __global__

defaults:
  - _self_
  - save: bq
  - llm: full

bm:
  cfg:
    name: buttermilk
    job: debugging
    logger: 
      type: gcp
      project: prosocial-443205
      location: us-central1
    tracing: 
      enabled: false
    verbose: true
    save_dest:
      type: gcp
      project: dmrc-analysis
      region: us-central1
      bucket: dmrc-analysis

    clouds:
      - type: gcp
        project: prosocial-443205
        region: us-central1
      - type: vertex
        project: dmrc-platforms
        region: us-central1
        bucket: dmrc-analysis

    secret_provider: 
      type: gcp
      project: dmrc-platforms
      models_secret: dev__llm__connections

    pubsub:
      type: gcp
      project: dmrc-platforms
      subscription: flow-sub

    run:
      platform: local
      max_concurrency: 32