defaults:
  - config
  - local
  - _self_

name: buttermilk
job: testing
ui: console

bm:
  _target_: buttermilk.bm.BM

  run_info:
    name: ${name}
    job: ${job}
    platform: local
    max_concurrency: 16
    flow_api: http://flow:8000/flow/
    
  clouds:
    - type: gcp
      project: prosocial-443205
      verbose: false
    - type: vertex
      project: prosocial-443205
      region: us-central1
      location: us-central1
      bucket: prosocial-dev
        

save:
  type: bq
  dataset: prosocial-443205.testing.flow
  db_schema: flow.json


flows:
  test:
    source: hate development
    steps:
      - name: context_owl
        description: Spots little things that are easy to miss.
        agent: LLMAgent
        num_runs: 1
        save: ${save}
        parameters:
          template: owl
        variants:
          model: ${llms.general}