defaults:
  - config
  - local
  - _self_

name: development
job: testing
ui: console

bm:
  _target_: buttermilk.bm.BM

  run_info:
    name: ${name}
    job: ${job}
    platform: local
    max_concurrency: 16
    flow_api: http://flow:8000/flow/
    
  clouds:
    - type: gcp
      project: prosocial-443205
      verbose: true
    - type: vertex
      project: prosocial-443205
      region: us-central1
      location: us-central1
      bucket: prosocial-dev
        

save:
  type: bq
  dataset: prosocial-443205.testing.flow
  db_schema: flow.json


flows:
  test:
    name: test
    description: Test flow
    source: hate development
    save: ${save}
    agents:
      - owl:
        role: OWLS
        name: "🦉 Owl"
        description: They will speak up if needed. You don't need to call on them.
        agent_obj: LLMAgent
        save:
        num_runs: 1
        parameters:
          template: owl
        variants:
          model: ${llms.cheap}
        inputs:
          history: "*[]"
