defaults:
  - config
  - local
  - _self_
  - llms: lite

name: buttermilk
job: testing
ui: console

bm:
  _target_: buttermilk.bm.BM

  run_info:
    name: ${name}
    job: ${job}
    platform: local
    max_concurrency: 16
    flow_api: http://flow:8000/flow/
    

save:
  type: bq
  dataset: prosocial-443205.testing.flow
  db_schema: flow.json


flows:
  test:
    source: hate development
    steps:
      - name: context_owl
        description: Spots little things that are easy to miss.
        agent: LLMAgent
        num_runs: 1
        save: ${save}
        variants:
          template: owl
          model: ${llms.general}