# Default file storage configuration template
# Can be used for local development or file-based workflows

type: file
path: ${oc.env:BUTTERMILK_DATA_PATH,./data/}
glob: "**/*"
max_records_per_group: -1

# Common storage settings
randomize: true
batch_size: 100
auto_create: true