name: automod
job: judge
hydra:
  job:
    env_set:
      PF_WORKER_COUNT: 1
      PF_BATCH_METHOD: fork
project:
  secret_provider: azure
  logger: gcp
  verbose: true
  models_secret: models
  save_dest: gcp
  save_dir:
  gcp:
    project: dmrc-analysis
    region: us-central1
    bucket: dmrc-analysis
  azure:
    vault: https://suzorvault.vault.azure.net/
    resource_group: rg-suzor_ai
  aws:
    secret_name: secret
    region: us-east-1