defaults:
  - _self_

name: automod
job:
logger: 
  type: gcp
tracing: 
  enabled: true
verbose: false
save_dest:
  type: gcp
  project: dmrc-analysis
  region: us-central1
  bucket: dmrc-analysis
secret_provider: 
  type: azure
  vault: https://suzorvault.vault.azure.net/
  resource_group: rg-suzor_ai
  models_secret: models

run:
  platform: local
  max_concurrency: 32