name: automod
job: judge
hydra:
  job:
    env_set:
      PF_WORKER_COUNT: 24
      PF_BATCH_METHOD: fork
project:
  secret_provider: azure
  logger: gcp
  models_secret: models
  save_dest: gcp
  save_dir:
  gcp:
    project: dmrc-analysis
    region: us-central1
    bucket: dmrc-analysis
  azure:
    vault: https://suzorvault.vault.azure.net/
    resource_group: rg-suzor_ai
  aws:
    secret_name: secret
    region: us-east-1
run:
  dataset:
    uri:
    columns:
  tasks:
    judge:
      standards:
      template: judge.prompty
      results:
        dest: bq
        dataset: dmrc-analysis.toxicity.standards
        schema: flows/common/rules.schema.json
      models:
      - gpt4o
      - llama31_70b
      - sonnet
      - gemini15pro
      - opus
      - llama31_405b
      - llama31_8b
      - haiku
    metrics:
      dest: bq
      dataset: dmrc-analysis.toxicity.metrics
      schema: flows/common/metrics.schema.json
