# Common agent configurations used across multiple flows
# These can be overridden in specific flows as needed

judge:
  _target_: /agents/judge
  role: JUDGE
  name: "Judge"
  description: "Evaluates content against specified criteria"
  agent_obj: buttermilk.agents.judge.JudgeAgent
  parameters:
    template: judge  # Default template, can be overridden
    model: ${llms.default}
    
synth:
  _target_: /agents/synth
  role: SYNTH
  name: "Synthesis Expert"
  description: "Synthesizes findings from multiple sources"
  agent_obj: buttermilk.agents.general.GeneralAgent
  parameters:
    template: synthesise
    model: ${llms.default}
    
differences:
  _target_: /agents/differences
  role: DIFFERENCES
  name: "Difference Analyst"
  description: "Analyzes differences between judgments"
  agent_obj: buttermilk.agents.general.GeneralAgent
  parameters:
    template: differences
    model: ${llms.default}