# @package _global_
# Batch execution configuration
defaults:
  - /local
  - _self_

name: bm_api
job: flows

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: api
  ui: web
  human_in_loop: ${human_in_loop}
  save: ${save}
  flows: {}
  
