# @package _global_
defaults:
  - /local
  - /flows@run.flows:
    - trans
  
run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: api
  ui: web
  human_in_loop: true
  flows: {}

  name: bm_api
  job: flows
