# @package _global_
defaults:
  - /local
  # Don't hardcode flows - let user specify via command line
  
run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: api
  ui: web
  human_in_loop: true
  flows: {}  # Will be populated by command line args

  name: bm_api
  job: flows
