# @package _global_
defaults:
  - _self_
  - /local

  
run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: api
  ui: web
  human_in_loop: true

  name: bm_api
  job: flows

  flows: ${flows}
