# @package _global_
# Batch execution configuration
defaults:
  - /local
  - _self_

name: bm_batch
job: flows

max_records: -1

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: batch
  ui: console
  human_in_loop: false
  save: ${save}
  flows: {}
