# @package _global_
# Batch execution configuration
defaults:
  - /local
  - override /llms: full
  - _self_
  

name: bm_batch
job: flows

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: batch
  ui: console
  human_in_loop: false
  save: ${save}
  flows: {}
