# Batch execution configuration
defaults:
  - /local
  - _self_
  # ... other defaults

name: bm_console
job: development

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  save: ${save}
  mode: console
  ui: console
  human_in_loop: true
