# @package _global_
defaults:
  - /local

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: console
  ui: console
  human_in_loop: true

  name: ${bm.name}
  job: ${bm.job}

  flows: ${flows}
