# Batch execution configuration
defaults:
  # ... other defaults
  - /flows/criteria@batch.parameters.criteria:
      - trans

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  save: ${save}
  mode: console
  ui: console
  human_in_loop: true
