# @package _global_
defaults:
  - /local
  - _self_

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: console
  ui: console
  human_in_loop: true

  name: bm_console
  job: development

  flows: ${flows}
