# @package _global_
name: simplerunner
job: flows

runner:
  _target_: buttermilk.runner.simple.Sequencer
  bm:
    _target_: buttermilk.BM
    cfg:
      name: ${name}
      job: ${job}
      logger:
      clouds:
      tracing:
      run:
        platform: local
        max_concurrency: 16
        flow_api: http://flow:8000/flow/
  data:
  interface: buttermilk.ui.console.CLIUserAgent
  flows:
    simple:
      source: development flow

      steps:
        - name: fetch
          agent: buttermilk.agents.fetch.Fetch
          description: fetch urls and stored records for the chat
          inputs:
            prompt: q

        - name: judge
          description: Applies criteria to content.
          _target_: buttermilk.agents.llm.LLMAgent
          num_runs: 2
          variants:
            template: judge
            model: gemini2flashthinking
            criteria: criteria_ordinary
            formatting: json_rules
          inputs:
            record: fetch.record

        - name: feedback
          description: QA for mistakes.
          _target_: buttermilk.agents.llm.LLMAgent
          num_runs: 1
          variants:
            template: feedback
            model: ${llms.general}
          inputs:
            history: history

        - name: synth
          _target_: buttermilk.agents.llm.LLMAgent
          description: Synthesizes draft answers.
          num_runs: 1
          save: ${save}
          variants:
            model: gemini2flashthinking
            template: synthesise_judger
            criteria: criteria_ordinary
            formatting: json_rules
          inputs:
            record: fetch.record
            instructions: >
              Carefully apply EACH of the CRITERIA in order and provide a COMPLETE and SPECIFIC explanation about whether the particular rule has been violated and how. Use quotes from the content where necessary to support your analysis.
            answers: judge
            feedback: feedback

        - name: eval
          _target_: buttermilk.agents.llm.LLMAgent
          num_runs: 1
          description: show differences between answers
          variants:
            template: differences
            model: gemini2flashthinking
            criteria: >
              Evaluate how well the provided content aligns with the rules.
          inputs:
            content: content
            answers:
              - judge
              - synth
            feedback: feedback
