# @package _global_
# Test configuration for API mode with minimal setup

defaults:
  - /local
  - /llms@bm.llms: lite

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: api
  ui: web
  human_in_loop: false  # Disable for testing
  name: bm_test_api
  job: test
  flows:
    tox:
      _target_: buttermilk.orchestrators.groupchat.AutogenOrchestrator
      name: "tox_test"
      description: "Test toxicity flow for MCP testing"
      orchestrator: buttermilk.orchestrators.groupchat.AutogenOrchestrator
      parameters:
        criteria: ["criteria_ordinary"]
      agents:
        judge:
          _target_: buttermilk._core.config.AgentConfig
          agent_class: buttermilk.agents.judge.Judge
          role: judge
          description: "Judge agent for testing"
          parameters: {}
      observers: {}
      storage:
        type: mock  # Use mock storage for testing