# @package _global_

defaults:
  - _self_


start_from: 5000

name: vectoriser
job: zotero
vectoriser:
  _target_: buttermilk.data.vector.ChromaDBEmbeddings
  persist_directory: "/home/nic/data/prosocial_zot/files"
  collection_name: "prosocial_zot"
  embedding_model: "text-embedding-large-exp-03-07"
  dimensionality: 3072
  arrow_save_dir: "/home/nic/data/prosocial_zot/data"
  
chunker:
  _target_: buttermilk.data.vector.DefaultTextSplitter
  chunk_size: 9000
  chunk_overlap: 3000

input_docs:
  _target_: buttermilk.tools.zotero.ZotDownloader
  library: "2281727"
  save_dir: "/home/nic/data/prosocial_zot/pdfs"

preprocessor:
  _target_: buttermilk.tools.pdf_extractor.PdfTextExtractor
  save_dir: "/home/nic/data/prosocial_zot/pdfs"

processor:
  _target_: buttermilk.tools.citator.Citator
  model: "gemini25pro"

  