"""
Utility to silence noisy logs from various libraries.
This can be imported and used directly without waiting for the main BM setup_logging process.
"""

import logging
import re


class WeaveApplicationErrorFilter(logging.Filter):
    """Filter to suppress weave errors that are actually application errors being traced by weave.
    
    This filter allows weave infrastructure errors (like upload failures) to pass through
    while suppressing duplicate application errors that weave is just reporting on.
    """
    
    # Patterns for application errors that weave is just reporting on (should be filtered)
    APPLICATION_ERROR_PATTERNS = [
        r"Return type .* not in return types",
        r"Error in autogen async wrapper",
        r"ValueError: Return type.*not in return types",
        r"weave: Return type.*not in return types",
        r"weave: Error in autogen async wrapper",
    ]
    
    # Patterns for genuine weave infrastructure errors (should be preserved)
    INFRASTRUCTURE_ERROR_PATTERNS = [
        r"upload failed",
        r"connection failed",
        r"authentication failed", 
        r"network error",
        r"timeout",
        r"rate limit",
        r"api error",
        r"wandb.*error",
    ]
    
    def __init__(self):
        super().__init__()
        self.app_error_regexes = [re.compile(pattern, re.IGNORECASE) for pattern in self.APPLICATION_ERROR_PATTERNS]
        self.infra_error_regexes = [re.compile(pattern, re.IGNORECASE) for pattern in self.INFRASTRUCTURE_ERROR_PATTERNS]
    
    def filter(self, record):
        """Return False to filter out (suppress) the log record, True to keep it."""
        message = record.getMessage()
        
        # First check if this is a genuine infrastructure error - always keep these
        for regex in self.infra_error_regexes:
            if regex.search(message):
                return True
        
        # Then check if this is an application error being reported by weave - filter these out
        for regex in self.app_error_regexes:
            if regex.search(message):
                return False
        
        # Default: keep all other weave messages
        return True


def silence_task_logs():
    """
    Silence the noisy logging messages from task execution, fsspec, and autogen_core.
    This is especially useful for quieting the console output from asyncio tasks.
"""

    # --- Quieten overly verbose libraries directly ---

    logging.getLogger("googleapiclient").setLevel(logging.WARNING)
    logging.getLogger("google.auth").setLevel(logging.WARNING)
    logging.getLogger("urllib3").setLevel(logging.WARNING)
    logging.getLogger("requests").setLevel(logging.WARNING)
    # Silence noisy asyncio, fsspec, and autogen_core logs
    logging.getLogger("asyncio").setLevel(logging.ERROR)
    logging.getLogger("fsspec").setLevel(logging.ERROR)
    logging.getLogger("autogen_core").setLevel(logging.WARNING)
    logging.getLogger("autogen_core._single_threaded_agent_runtime").setLevel(logging.ERROR)
    # Silence task execution logging from asyncio.tasks
    logging.getLogger("asyncio.tasks").setLevel(logging.ERROR)
    # Silence any other SingleThreadedAgentRuntime related logs
    logging.getLogger("Task").setLevel(logging.ERROR)
    # Add any other libraries that are too noisy

    # Turn off some particularly annoying (and unresolvable) warnings generated by upstream libraries
    import warnings

    warnings.filterwarnings(
        action="ignore",
        message="unclosed",
        category=ResourceWarning,
    )
    warnings.filterwarnings(
        action="ignore",
        module="msal",
        category=DeprecationWarning,
    )
    warnings.filterwarnings(
        action="ignore",
        message="The `dict` method is deprecated",
        module="promptflow-tracing",
        category=DeprecationWarning,
    )
    warnings.filterwarnings(
        action="ignore",
        module="traceloop",
        category=DeprecationWarning,
    )
    # warnings.filterwarnings(
    #     action="ignore",
    #     message="Passing field metadata as keyword arguments is deprecated",
    # )
    warnings.filterwarnings(
        action="ignore",
        message="`sentry_sdk.Hub` is deprecated",
        category=DeprecationWarning,
    )
    # warnings.filterwarnings(
    #     action="ignore",
    #     message="Support for class-based `config` is deprecated",
    #     category=DeprecationWarning,
    # )
    warnings.filterwarnings(
        action="ignore",
        module="marshmallow",
        category=Warning,
    )
    warnings.filterwarnings(
        action="ignore",
        message="jsonschema.RefResolver is deprecated",
        # category=DeprecationWarning,
        module="flask_restx",
    )
    warnings.filterwarnings(
        action="ignore",
        message="CropBox missing from",
    )

    # Silence asyncio task execution logs
    logging.getLogger("asyncio").setLevel(logging.ERROR)
    logging.getLogger("asyncio.tasks").setLevel(logging.ERROR)
    logging.getLogger("Task").setLevel(logging.ERROR)

    # Weave logging with selective filtering
    # Instead of suppressing all weave errors, use custom filter to distinguish
    # between application errors (that weave is just reporting) and weave infrastructure errors
    weave_filter = WeaveApplicationErrorFilter()
    
    # Apply selective filtering to main weave loggers
    weave_loggers = [
        "weave",
        "weave.trace", 
        "weave.client",
        "weave.weave_client",
        "weave.trace.weave_client",
    ]
    
    for logger_name in weave_loggers:
        logger = logging.getLogger(logger_name)
        logger.setLevel(logging.WARNING)  # Allow warnings and errors, but filter selectively
        logger.addFilter(weave_filter)
    
    # For weave API loggers, still suppress completely since they're mainly connection noise
    logging.getLogger("weave.wandb_api").setLevel(logging.ERROR)
    logging.getLogger("weave.api").setLevel(logging.ERROR)
    
    # Additional weave-related loggers that might output connection errors
    logging.getLogger("httpx").setLevel(logging.ERROR)
    logging.getLogger("httpcore").setLevel(logging.ERROR)

    # Silence fsspec logs
    logging.getLogger("fsspec").setLevel(logging.ERROR)
    logging.getLogger("fsspec.asyn").setLevel(logging.ERROR)

    # Silence autogen_core logs
    logging.getLogger("autogen_core").setLevel(logging.WARNING)
    logging.getLogger("autogen_core._single_threaded_agent_runtime").setLevel(logging.ERROR)

# Automatically silence logs when module is imported
silence_task_logs()

if __name__ == "__main__":
    print("Silenced noisy task execution logs.")
